// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_cgocheck2_on.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_cgocheck2_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.cgocheck2
// +build goexperiment.cgocheck2

package goexperiment

const CgoCheck2 = true
const CgoCheck2Int = 1
