// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_pagetrace_off.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_pagetrace_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.pagetrace
// +build !goexperiment.pagetrace

package goexperiment

const PageTrace = false
const PageTraceInt = 0
