// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_heapminimum512kib_on.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_heapminimum512kib_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.heapminimum512kib
// +build goexperiment.heapminimum512kib

package goexperiment

const HeapMinimum512KiB = true
const HeapMinimum512KiBInt = 1
