// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_arenas_on.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_arenas_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.arenas
// +build goexperiment.arenas

package goexperiment

const Arenas = true
const ArenasInt = 1
