// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_loopvar_off.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_loopvar_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.loopvar
// +build !goexperiment.loopvar

package goexperiment

const LoopVar = false
const LoopVarInt = 0
