// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_heapminimum512kib_off.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goexperiment/exp_heapminimum512kib_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.heapminimum512kib
// +build !goexperiment.heapminimum512kib

package goexperiment

const HeapMinimum512KiB = false
const HeapMinimum512KiBInt = 0
