// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/internal/notsha256/sha256block_decl.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/internal/notsha256/sha256block_decl.go:1
// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !purego && (386 || amd64 || ppc64le || ppc64)
// +build !purego
// +build 386 amd64 ppc64le ppc64

package notsha256

//go:noescape
func block(dig *digest, p []byte)
