// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/internal/bio/buf_nommap.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/internal/bio/buf_nommap.go:1
// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !aix && !darwin && !dragonfly && !freebsd && !linux && !netbsd && !openbsd && !(solaris && go1.20)

package bio

func (r *Reader) sliceOS(length uint64) ([]byte, bool) {
	return nil, false
}
