// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goarch/goarch_mips64le.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goarch/goarch_mips64le.go:1
// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package goarch

const (
	_ArchFamily          = MIPS64
	_DefaultPhysPageSize = 16384
	_PCQuantum           = 4
	_MinFrameSize        = 8
	_StackAlign          = PtrSize
)
