// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goarch/goarch_ppc64le.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/goarch/goarch_ppc64le.go:1
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package goarch

const (
	_ArchFamily          = PPC64
	_DefaultPhysPageSize = 65536
	_PCQuantum           = 4
	_MinFrameSize        = 32
	_StackAlign          = 16
)
