// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/abi/abi_riscv64.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/abi/abi_riscv64.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package abi

const (
	// See abi_generic.go.

	// X8 - X23
	IntArgRegs = 16

	// F8 - F23.
	FloatArgRegs = 16

	EffectiveFloatRegSize = 8
)
