// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/buildcfg/zbootstrap.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/buildcfg/zbootstrap.go:1
// Code generated by go tool dist; DO NOT EDIT.

package buildcfg

import "runtime"

const defaultGO386 = `sse2`
const defaultGOAMD64 = `v1`
const defaultGOARM = `7`
const defaultGOMIPS = `hardfloat`
const defaultGOMIPS64 = `hardfloat`
const defaultGOPPC64 = `power8`
const defaultGOEXPERIMENT = ``
const defaultGO_EXTLINK_ENABLED = ``
const defaultGO_LDSO = ``
const version = `go1.21.5`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
