// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/link/internal/riscv64/l.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/link/internal/riscv64/l.go:1
// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package riscv64

const (
	maxAlign  = 32 // max data alignment
	minAlign  = 1
	funcAlign = 8

	dwarfRegLR = 1
	dwarfRegSP = 2
)
