// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/at_sysnum_netbsd.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/at_sysnum_netbsd.go:1
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

import "syscall"

const unlinkatTrap uintptr = syscall.SYS_UNLINKAT
const openatTrap uintptr = syscall.SYS_OPENAT
const fstatatTrap uintptr = syscall.SYS_FSTATAT

const AT_REMOVEDIR = 0x800
const AT_SYMLINK_NOFOLLOW = 0x200

const UTIME_OMIT = (1 << 30) - 2
