// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/at_sysnum_freebsd.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/at_sysnum_freebsd.go:1
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

import "syscall"

const (
	AT_REMOVEDIR        = 0x800
	AT_SYMLINK_NOFOLLOW = 0x200

	UTIME_OMIT = -0x2

	unlinkatTrap       uintptr = syscall.SYS_UNLINKAT
	openatTrap         uintptr = syscall.SYS_OPENAT
	posixFallocateTrap uintptr = syscall.SYS_POSIX_FALLOCATE
)
