// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/eaccess_linux.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/eaccess_linux.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

import "syscall"

func Eaccess(path string, mode uint32) error {
	return syscall.Faccessat(AT_FDCWD, path, mode, AT_EACCESS)
}
