// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/nonblocking_js.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/nonblocking_js.go:1
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build js && wasm

package unix

func IsNonblock(fd int) (nonblocking bool, err error) {
	return false, nil
}

func HasNonblockFlag(flag int) bool {
	return false
}
