// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/sysnum_linux_mips64x.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/syscall/unix/sysnum_linux_mips64x.go:1
// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build mips64 || mips64le

package unix

const (
	getrandomTrap     uintptr = 5313
	copyFileRangeTrap uintptr = 5320
)
