// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/generate.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/generate.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build generate

package ssa

//go:generate go run -C=_gen .
