// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValuePPC64latelower(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockPPC64latelower(b *Block) bool { panic("unused during bootstrap") }
