// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValueAMD64latelower(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockAMD64latelower(b *Block) bool { panic("unused during bootstrap") }
