// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValueLOONG64(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockLOONG64(b *Block) bool { panic("unused during bootstrap") }
