// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValueRISCV64(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockRISCV64(b *Block) bool { panic("unused during bootstrap") }
