// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValueAMD64splitload(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockAMD64splitload(b *Block) bool { panic("unused during bootstrap") }
