// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValue386splitload(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlock386splitload(b *Block) bool { panic("unused during bootstrap") }
