// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/pkgbits/flags.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/pkgbits/flags.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pkgbits

const (
	flagSyncMarkers = 1 << iota // file format contains sync markers
)
