// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/pkgbits/support.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/internal/pkgbits/support.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pkgbits

import "fmt"

func assert(b bool) {
	if !b {
		panic("assertion failed")
	}
}

func errorf(format string, args ...interface{}) {
	panic(fmt.Errorf(format, args...))
}
