// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/_gen/dec64Ops.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/_gen/dec64Ops.go:1
// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

var dec64Ops = []opData{}

var dec64Blocks = []blockData{}

func init() {
	archs = append(archs, arch{
		name:    "dec64",
		ops:     dec64Ops,
		blocks:  dec64Blocks,
		generic: true,
	})
}
