// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/_gen/decOps.go

//line /Users/bhavyabhatt/Desktop/bhavya/projects/go-plus/src/cmd/compile/internal/ssa/_gen/decOps.go:1
// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

var decOps = []opData{}

var decBlocks = []blockData{}

func init() {
	archs = append(archs, arch{
		name:    "dec",
		ops:     decOps,
		blocks:  decBlocks,
		generic: true,
	})
}
